### ISSUE TITLE
remove unused usings

### ISSUE THREAD

**Issue by incredibleLeitman** [KiwiCase/Quiz-Maker#1]
https://github.com/KiwiCase/Quiz-Maker/blob/608949a6a482d338eb822dd7b020837eb48ce503/Quiz-Maker/Program.cs#L1-L2

You can right click on the using-part and select "Remove and Sort usings" or use the default shortcut "Ctrl+R, Ctrl + G"
Make sure you keep your usings straight in all your files

**Comment by KiwiCase** [comment]
Thanks, and done! 👍

**Comment by KiwiCase** [comment]
Resolved.
