### ISSUE TITLE
Better move into loop

### ISSUE THREAD

**Issue by mayisa87** [KiwiCase/Quiz-Maker#11]
https://github.com/KiwiCase/Quiz-Maker/blob/3f7116fe6efef03464d619da0703e6094d3bc4be/Quiz-Maker/UserInterface.cs#L26

It is better to have only one condition in your loop condition. So there are several ways how to use a while loop:

- while(condition) --> loop as long as this ONE condition matches
- while(true) --> loop as long as there is somewhere a "break;" in your loop that interupts it
- while(boolFlag) --> use a bool variable that is first set to true (to enter loop at least once) and set it to false if you want the loop to stop.

So you could maybe use option 2, so you will enter the loop for sure at least once. Inside you do:

1. Read user input into answer variable
2. check if input was valid and not >5 (use a consant!!!!)
3. if this is not the case, loop will continue anyway, if input was ok, you can do a break and stop looping.

**Comment by CDProjects** [comment]
Thank you so much for the feedback Isabella! I'm still fairly sick but hopefully I'll be right to continue this tomorrow. Have a great weekend 😃

**Comment by KiwiCase** [comment]
I believe I've resolved this issue as follows:

```
/// <summary>
/// Prompts the user for the number of questions they want in their quiz.
/// Uses an infinite loop to validate the input, ensuring it's a valid integer and within the allowed range.
/// Exits the loop once a valid input is received.
/// </summary>
/// <returns>The number of questions the user wants in the quiz, not exceeding the maximum limit.</returns>
public static int HowManyQuestions()
{
    const int MaxQuestions = 5; // Constant for maximum allowed questions
    int answer = 0;

    Console.WriteLine($"How many questions would you like in your Quiz? \n{MaxQuestions} is the maximum questions allowed: ");
    while (true) // Infinite loop, exits only when valid input is received
    {
        string input = Console.ReadLine();
        if (Int32.TryParse(input, out answer) && answer > 0 && answer <= MaxQuestions)
        {
            break; // Exit loop when input is valid and within the allowed range
        }
        else
        {
            Console.WriteLine($"This is not a valid input. \nHow many questions would you like in your Quiz? \n{MaxQuestions} is the maximum questions allowed: ");
        }
    }
    return answer;
}
```
I've implemented a MaxQuestions constant for the maximum number of questions allowed and an infinite loop (while (true)) which only breaks when a valid and acceptable input is received.
