### ISSUE TITLE
Not a good name

### ISSUE THREAD

**Issue by AlexKap23** [KiwiCase/Quiz-Maker#13]
https://github.com/KiwiCase/Quiz-Maker/blob/e059955405fb773a4c84553d9377f9d5a8fac58f/Quiz-Maker/UserInterface.cs#L45

Name of methods should contain a verb that points to the action of the method. In this case, a name like InputNumberOfQuestions would be better.

Same applies to method UserQuestionsAndAnswers

**Comment by KiwiCase** [comment]
Issue #13 not a good name resolved pushed to GH.
