### ISSUE TITLE
else case is redundant

### ISSUE THREAD

**Issue by AlexKap23** [KiwiCase/Quiz-Maker#14]
https://github.com/KiwiCase/Quiz-Maker/blob/e059955405fb773a4c84553d9377f9d5a8fac58f/Quiz-Maker/UserInterface.cs#L58-L61

Since your if case is breaking out of the loop you don't even need an else case. Remove it and place it's content immediately after the if case. This will make your code more readable

**Comment by KiwiCase** [comment]
Issue #14 else case is redundant resolved pushed to GH.
