### ISSUE TITLE
Declare constants 

### ISSUE THREAD

**Issue by AlexKap23** [KiwiCase/Quiz-Maker#15]
https://github.com/KiwiCase/Quiz-Maker/blob/e059955405fb773a4c84553d9377f9d5a8fac58f/Quiz-Maker/UserInterface.cs#L225

declare constants for "yes" and "y" and use them instead of hardcoded strings

**Comment by KiwiCase** [comment]
Issue #15 Declare constants resolved - pushed to GH.
