### ISSUE TITLE
Is this id property needed?

### ISSUE THREAD

**Issue by AlexKap23** [KiwiCase/Quiz-Maker#16]
https://github.com/KiwiCase/Quiz-Maker/blob/e059955405fb773a4c84553d9377f9d5a8fac58f/Quiz-Maker/QuestionAndAnswers.cs#L10

Do you use this id property anywhere? Is this important for json serialization?

**Comment by KiwiCase** [comment]
Issue #16 Is this id property needed - resolved. Pushed to GH
