### ISSUE TITLE
Avoid using Environment.Exit(0)

### ISSUE THREAD

**Issue by AlexKap23** [KiwiCase/Quiz-Maker#17]
https://github.com/KiwiCase/Quiz-Maker/blob/e059955405fb773a4c84553d9377f9d5a8fac58f/Quiz-Maker/UserInterface.cs#L32

Environment.Exit(0) exits the application immediatelly without letting the compiler do some clean up first. Since you are handling the mode 3 on the switch case on program, just return the value 3 and break out of the loop.

In general your method ChooseMode could be converted to ValidateQuizMode, and just validate that the user's input is one of the valid options (1,2,3) and just return the valid values back. 

we also suggest to make use of an enum or use constants to avoid having magic numbers in your program.

**Comment by KiwiCase** [comment]
Issue #17 Avoid using Environment.Exit(0) pushed to GitHub.
