### ISSUE TITLE
Why don't you move those methods into QuizLogic.cs?

### ISSUE THREAD

**Issue by AlexKap23** [KiwiCase/Quiz-Maker#18]
https://github.com/KiwiCase/Quiz-Maker/blob/e059955405fb773a4c84553d9377f9d5a8fac58f/Quiz-Maker/QuestionAndAnswers.cs#L19-L29

They are business logic methods and can be moved to QuizLogic.cs 

Is there any idea behind placing them into your QuestionAndAnswers?

**Comment by KiwiCase** [comment]
No idea though I believe at the time of implementation, I intended to move it to QuizLogic.cs, but I went down another rabbit hole and forgot - I've now moved these methods to QuizLogic.cs - thanks!
