### ISSUE TITLE
this probably should be in a loop

### ISSUE THREAD

**Issue by incredibleLeitman** [KiwiCase/Quiz-Maker#2]
https://github.com/KiwiCase/Quiz-Maker/blob/95c7df4034a5e26adb4e13faa6122dfdb95821a0/Quiz-Maker/Program.cs#L11-L13

**Comment by incredibleLeitman** [comment]
![image](https://user-images.githubusercontent.com/24638443/203067293-3c103a79-0548-4593-95a8-ca4eeff2da7c.png)
Although this is loop now, you basically only override the given QnA object every time.

Why does this method even take a QuestionAndAnswers param in the first place? 🤔 
I think what you actually want to do i return a list of QnA objects and push one element for each step of the loop?

**Comment by KiwiCase** [comment]
I think so yes - my code wasn't producing the desired results and is on my list of things to look at. I will definitely discuss this more with Florian at today's call. Thank you!

**Comment by mayisa87** [comment]
This issue is still open. 

https://github.com/KiwiCase/Quiz-Maker/blob/1ae8f3952e658d8efc92527d285fd1fe52d7aa82/Quiz-Maker/Program.cs#L12

Currently you only create one Object and return it to the Program. You could create a List of Questions and return it to the program.

**Comment by KiwiCase** [comment]
Resolved UserInterface.cs

```
public static int HowManyQuestions()
{
    const int MaxQuestions = 5; // Constant for maximum allowed questions
    int answer = 0;

    Console.WriteLine($"How many questions would you like in your Quiz? \n{MaxQuestions} is the maximum questions allowed: ");
    while (true) // Infinite loop, exits only when valid input is received
    {
        string input = Console.ReadLine();
        if (Int32.TryParse(input, out answer) && answer > 0 && answer <= MaxQuestions)
        {
            break; // Exit loop when input is valid and within the allowed range
        }
        else
        {
            Console.WriteLine($"This is not a valid input. \nHow many questions would you like in your Quiz? \n{MaxQuestions} is the maximum questions allowed: ");
        }
    }
    return answer;
}
```
Program.cs

`int numberOfQuestions = UserInterface.HowManyQuestions();`
