### ISSUE TITLE
use a loop to input a number of answers

### ISSUE THREAD

**Issue by incredibleLeitman** [KiwiCase/Quiz-Maker#4]
https://github.com/KiwiCase/Quiz-Maker/blob/95c7df4034a5e26adb4e13faa6122dfdb95821a0/Quiz-Maker/UserInterface.cs#L33-L52

related to #3

**Comment by KiwiCase** [comment]
Thanks for the suggestion, I was thinking though, is it necessary to loop this when I can call this method each time for each different question? I'll push to GH to give you a better idea of what I was intending to do - thanks!

**Comment by KiwiCase** [comment]
Although now I am beginning to see why a loop might be necessary. The current format for my QnA cards doesn't look like it will work as intended. I'll keep at it :D

**Comment by incredibleLeitman** [comment]
Yes, to realize this issue you will need to modify your QnA card first
-> #3

**Comment by KiwiCase** [comment]
Will discuss with Florian at today's call - thanks Michael 🙏

**Comment by mayisa87** [comment]
So this issue is still open. You could whether define a fixed number of answers to be entered or ask user how many answers should be entered. 
For sure you need to think about, how the user should set the right answer, like last answer always will be the right one... or show answers entered and ask user which one is the right one. There are different ways to implement this for sure :)

**Comment by KiwiCase** [comment]
Have resolved this issue:

           ```
 // Loop to collect the incorrect answers
            List<string> incorrectAnswers = new List<string>();
            for (int i = 1; i <= 3; i++)
            {
                Console.WriteLine($"Please type your {i} false answer: ");
                string falseAnswer = Console.ReadLine();
                incorrectAnswers.Add(falseAnswer);
            }

            QuestionAndAnswers userQnA = new QuestionAndAnswers(userQuestion, correctAnswer);
            userQnA.IncorrectAnswers.AddRange(incorrectAnswers);

            return userQnA;
```

Thanks!

**Comment by incredibleLeitman** [comment]
I consider this issue as resolved so you may close it,
but keep in mind that we don't like hardcoded magic numbers 😏 

The definition of how many wrong answers there are should be defined in a constant 👆

**Comment by KiwiCase** [comment]
> I consider this issue as resolved so you may close it, but keep in mind that we don't like hardcoded magic numbers 😏
> 
> The definition of how many wrong answers there are should be defined in a constant 👆

Notes, thanks!
