### ISSUE TITLE
keep your code clean

### ISSUE THREAD

**Issue by incredibleLeitman** [KiwiCase/Quiz-Maker#5]
- remove unused imports
https://github.com/KiwiCase/Quiz-Maker/blob/ec6933e970f895970194f6c91d51dde62d1c14db/Quiz-Maker/QuestionAndAnswers.cs#L1-L5

- remove newlines
https://github.com/KiwiCase/Quiz-Maker/blob/ec6933e970f895970194f6c91d51dde62d1c14db/Quiz-Maker/QuestionAndAnswers.cs#L10

- remove unused variables
https://github.com/KiwiCase/Quiz-Maker/blob/ec6933e970f895970194f6c91d51dde62d1c14db/Quiz-Maker/QuestionAndAnswers.cs#L12

**Comment by incredibleLeitman** [comment]
![image](https://user-images.githubusercontent.com/24638443/203070101-0b95a78c-7b3c-4e75-b037-7ee3d5772540.png)
- remove unused class files

**Comment by KiwiCase** [comment]
Updated! I completely forgot about my GetQuestionsAndAnswer class as I removed it from my views, didn't delete it. It has nows been deleted - thanks  Michael.

**Comment by KiwiCase** [comment]
I have resolved this and removed the unnecessary lines of code 👍

**Comment by incredibleLeitman** [comment]
good work :D

But remember to reference the solved issue in the corresponding commit message to keep track of the changes
