### ISSUE TITLE
Refactor shuffle function

### ISSUE THREAD

**Issue by incredibleLeitman** [KiwiCase/Quiz-Maker#6]
I don't know, if this should be inside of the logic part of your code instead of the QuestionAndAnswers class directly,
but do you understand, what is going on under the hood here?
https://github.com/KiwiCase/Quiz-Maker/blob/ec6933e970f895970194f6c91d51dde62d1c14db/Quiz-Maker/QuestionAndAnswers.cs#L24-L32

Especially this line?
> list.Sort((x, y) => rng.Next(2) * 2 - 1);   // shuffles list

If not, you should definitely rewrite this in order to make it more read- and understandable, you other readers and especially for yourself :D

**Comment by KiwiCase** [comment]
Thanks for your patience Michael and apologies this was closed! OK, so this has been resolved here:

```
private static List<string> ShuffleAnswers(QuestionAndAnswers userQnA, out int correctIndex)
{
    List<string> answers = new List<string>(userQnA.IncorrectAnswers);
    answers.Add(userQnA.CorrectAnswer);
    Random ran = new Random();
    answers = answers.OrderBy(_ => ran.Next()).ToList();
    correctIndex = answers.IndexOf(userQnA.CorrectAnswer);
    return answers;
}
```

The OrderBy method with a random key shuffles the answers 👍

**Comment by incredibleLeitman** [comment]
This is nice, especially since you have removed the creation of a random generator inside the function as mentioned in #12 👍 

However, there are still a few things to do:
- why do you provide "correctIndex"? And even more, why is this an out parameter? As far as I see you don't even use it when you call this function?
- Shuffling an index using OrderBy works perfectly fine and is very common, 
however do you really know what is going on there? You can leave that for now, but if you have some spare time you could look into a shuffle algorithm called "Fisher-Yates" -> This can be implemented very easily just using a plain for loop and allows every reader to perfectly understand what is happening under the hood :D

**Comment by KiwiCase** [comment]
Thanks for pointing these things out! I've amended my code accordingly regarding the Fisher-Yates shuffle.

Regarding correctIndex - I believe, and correct me if I am wrong, that it's used to track the position of the correct answer in the shuffled list of answers and it's used in the CheckAnswer method to compare the user's choice against the index of the correct answer in the shuffled list.

The out parameter is used because the ShuffleAnswers method changes the value of correctIndex which is the new position of the correct answer after shuffling - it needs to be accessed in the AskQuestion method to compare in the AskQuestion method, 

Is there an easier, better way to do this? Thanks!

**Comment by incredibleLeitman** [comment]
There are a few points on the current implementation:
1. you declare "correctIndex" as an input parameter which means when you call the function you need to provide the actual value which get overwritten within the function (which is usually a strange side effect and very hard to read and keep track --> usually you want a function to put in something and return something, not put in something get a return *and* change some of the things you put in)
```private static List<string> ShuffleAnswers(QuestionAndAnswers userQnA, out int correctIndex)```

Also, the correctIndex variable is just set by finding the index of the correct answer like
```correctIndex = answers.IndexOf(userQnA.CorrectAnswer);```
which could be done any time later like:

current code
```
int correctIndex;
List<string> shuffledAnswers = ShuffleAnswers(userQnA, out correctIndex); // changes correctIndex
```

could be
```
List<string> shuffledAnswers = ShuffleAnswers(userQnA);
int correctIndex = shuffledAnswers.IndexOf(userQnA.CorrectAnswer);
```

2. BUT 👆 this is potentially dangerous because "IndexOf" returns the first occurrence of the given value regarding the documentation which means if in theory the list contains multiple strings that are the same would lead to problems.
To mitigate this you could either ensure that only different answers are given when creating a new QuestionAndAnswer object or even combine multiple same answers into one.

**Comment by KiwiCase** [comment]
Resolved

```
public static List<string> ShuffleAnswers(QuestionAndAnswers userQnA)
{
    List<string> answers = new List<string>(userQnA.IncorrectAnswers);
    answers.Add(userQnA.CorrectAnswer);
    int n = answers.Count;
    for (int i = n - 1; i > 0; i--)
    {
        int j = random.Next(i + 1);
        (answers[j], answers[i]) = (answers[i], answers[j]);
    }
    return answers;
}
```
