### ISSUE TITLE
Clean up code: Check code for unnecessary empty lines

### ISSUE THREAD

**Issue by mayisa87** [KiwiCase/Quiz-Maker#7]
https://github.com/KiwiCase/Quiz-Maker/blob/1ae8f3952e658d8efc92527d285fd1fe52d7aa82/Quiz-Maker/QuestionAndAnswers.cs#L5

Have a look to your code and remove all unnecessary empty lines, this should be done always before check in.
A single empty line to structure is OK, but not multiple lines.

See video: https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560205

**Comment by KiwiCase** [comment]
Removed unnecessary empty lines (have left single empty lines however).
