### ISSUE TITLE
Rename to Question

### ISSUE THREAD

**Issue by mayisa87** [KiwiCase/Quiz-Maker#9]
https://github.com/KiwiCase/Quiz-Maker/blob/1ae8f3952e658d8efc92527d285fd1fe52d7aa82/Quiz-Maker/QuestionAndAnswers.cs#L4

**Comment by KiwiCase** [comment]
I think this is good to close as this encapsulates the necessary data for a quiz question, including the question text, correct answer, and a list of incorrect answers? Thanks.
